name: Build ToM

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js, npm
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Documentation
        if: matrix.os == 'ubuntu-latest'
        uses: mbruno46/websmith.js@main
        with:
          config: './doc/config.json'
          build: './doc/build'
          
      - name: Install dependecies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
        run: |
          npm run release
